name: Commitlint
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
    branches: [main]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 22.20
        uses: actions/setup-node@v4
        with:
          node-version: 22.20
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js
